-- WISTIA Supabase 초기 스키마
-- 실제 상담 접수 기능을 추가할 때만 사용합니다

create table if not exists public.consultation_requests (
  id bigint generated by default as identity primary key,
  product_key text not null,
  selected_events jsonb not null default '[]'::jsonb,
  final_price integer not null check (final_price >= 0),
  created_at timestamptz not null default now()
);

alter table public.consultation_requests enable row level security;

-- 공개 브라우저에서 직접 저장하지 않으며 서버 API를 통해서만 접근합니다
