const { chromium } = require(process.env.WISTIA_NODE_MODULES + '/playwright')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const OUT=path.join(__dirname,'qa')
fs.mkdirSync(OUT,{recursive:true})
;(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'})
 const report={checks:[],errors:[],brokenAssets:[]}
 try {
 for(const width of [390,1440,320,768]){
  const page=await browser.newPage({viewport:{width,height:width===320?568:width===768?1024:width===1440?900:844},reducedMotion:'reduce'})
  page.on('pageerror',e=>report.errors.push(e.message))
  page.on('response',r=>{if(r.url().startsWith('http://127.0.0.1:4173/')&&r.status()>=400)report.brokenAssets.push(r.url())})
  await page.goto('http://127.0.0.1:4173/?v=77#/',{waitUntil:'domcontentloaded'})
  await page.locator('.situation-home').waitFor()
  await page.evaluate(()=>document.fonts.ready)
  assert.equal(await page.locator('.situation-pill').count(),6,'home contains six situation choices')
  assert.equal(await page.locator('.situation-group').count(),2,'home separates video preparation and live singing')
  assert.deepEqual(await page.locator('.situation-group h2').allTextContents(),['영상으로 준비하기','현장에서 직접 부르기'])
  assert.equal(await page.locator('.situation-group>p').count(),2,'both home groups explain the difference')
  assert.equal(await page.locator('.situation-pill small').count(),6,'every home choice explains who it is for and how it is used')
  assert.deepEqual(await page.locator('.situation-pill').evaluateAll(nodes=>nodes.map(node=>node.getAttribute('href'))),['#/detail/wedding','#/film','#/detail/proposal','#/ar/self','#/ar/friend','#/detail/duo'])
  assert.ok(parseFloat(await page.locator('.wordmark>span').evaluate(node=>getComputedStyle(node).fontSize))<=20,'header wordmark stays compact')
  if(width<=768)assert.equal(await page.locator('.situation-group').evaluateAll(groups=>Math.abs(groups[0].getBoundingClientRect().top-groups[1].getBoundingClientRect().top)<2),true,'mobile home keeps both groups side by side')
  assert.equal(await page.locator('.home-hero,#finder,#services,main footer').count(),0,'home only contains the situation picker')
  if(width>320)assert.ok(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1),'home fits within one viewport')
  const routes=['/','/detail/wedding','/detail/duet-film','/detail/solo-film','/detail/proposal','/detail/solo','/detail/duo','/film','/song','/ar/self','/ar/friend','/event/wedding','/event/solo','/event/solo/friend','/event/duo','/event/duet-film','/event/solo-film','/event/proposal']
  for(const route of routes){
   await page.evaluate(hash=>location.hash='#'+hash,route)
   await page.waitForTimeout(90)
   assert.equal(await page.locator('h1').count(),1,'one h1 '+route)
   if(route==='/detail/duet-film'){
    assert.equal(await page.locator('.scene-grid li').count(),6)
    assert.equal(await page.locator('.scene-grid img').count(),7,'duet film composition uses every supplied scene')
    assert.deepEqual(await page.locator('.scene-copy h3').allTextContents(),['하객 메시지','두 사람의 인터뷰','우리 둘의 사진과 영상','녹음 메이킹 필름','노래 뮤비 클립','서로에게 전하는 편지'])
    assert.equal(await page.locator('.detail-inline-video').count(),0,'duet film uses the same result-card layout as the wedding film')
    assert.equal(await page.locator('.detail-result-media[data-video]').count(),1,'duet film opens its video from the matching result card')
    assert.equal(await page.locator('.detail-typography').count(),0,'duet film no longer uses a typography placeholder')
    assert.match(await page.locator('.composition-section h2').textContent(),/듀엣 축가 영상은/)
   }
   if(route==='/detail/solo-film'){
    assert.equal(await page.locator('.scene-grid img').count(),4,'solo film composition uses actual WISTIA frames')
    assert.equal(await page.locator('.song-film-cover').count(),1,'solo film hero contains a service image')
    assert.equal(await page.locator('.detail-typography').count(),0,'solo film no longer uses a typography placeholder')
   }
   if(route==='/detail/proposal'){
    assert.match(await page.locator('.detail-inline-video iframe').getAttribute('src'),/pTBfPEWlyZU/)
    assert.equal(await page.locator('.scene-grid img').count(),4,'proposal composition uses actual video frames')
   }
   if(route==='/film')assert.match(await page.locator('.picker-grid article').nth(1).locator('img').getAttribute('src'),/proposal-video-cover\.jpg/)
   if(route==='/ar/friend'){
    assert.equal(await page.locator('.option-banner').count(),2,'friend AR shows lyric-video and extra-person guidance')
    assert.match(await page.locator('.fixed-price a').getAttribute('href'),/#\/event\/solo\/friend$/)
   }
   if(route==='/ar/self')assert.equal(await page.locator('.process-image img').count(),4,'AR process uses four illustrated steps')
   if(route==='/event/solo/friend')assert.match(await page.locator('.friend-options').textContent(),/인원 추가.*상담 후 안내/s)
   if(route==='/detail/wedding'){
    assert.equal(await page.locator('.scene-grid li').count(),6)
    assert.equal(await page.locator('.scene-grid li').nth(5).locator('.scene-pair img').count(),2,'wedding letters show bride and groom half and half')
   }
   if(route==='/detail/wedding'){
    const ordered=await page.locator('.result-band,.composition-section,.worry-section,#process,.expertise,.reviews-section,.detail-next').evaluateAll(nodes=>nodes.map(n=>n.className||n.id))
    assert.deepEqual(ordered,['shell section composition-section','shell section worry-section','shell section','section reviews-section','detail-next section'])
    assert.equal(await page.locator('.detail-intro,.result-band,.expertise').count(),0,'repeated intro, result and expertise sections are removed')
    assert.equal(await page.locator('.detail-result-badge').textContent(),'이렇게 완성됩니다')
    assert.equal(await page.locator('.scene-copy .index').first().evaluate(el=>getComputedStyle(el,'::after').content),'none')
    assert.equal(await page.locator('.production-guide article').count(),3,'detail page contains production period, revision and delivery guidance')
    assert.equal(await page.locator('.review-capture:not([aria-hidden]) img').count(),11,'all real review captures are available in the carousel')
    assert.equal(await page.getByText(/모두 보기|11개/).count(),0,'review count and show-all link are removed')
    assert.equal(await page.locator('.detail-price-section,.booking-layout').count(),0,'detail page stops before package and reservation')
   }
   if(route==='/event/wedding'){
    assert.equal(await page.locator('.booking-layout').count(),1,'price page contains package and reservation')
    assert.equal(await page.locator('.booking-extra .option-choice').count(),2,'wedding price page contains two selectable additional options')
    assert.equal(await page.locator('.booking-extra .option-notice').count(),1,'additional revision is information only')
    assert.match(await page.locator('.booking-extra').textContent(),/3일 이내 빠른 작업/)
    assert.match(await page.locator('.booking-extra').textContent(),/기본 수정 3회까지 무료/)
    assert.match(await page.locator('.booking-extra').textContent(),/신부 입장곡 AR · 립싱크 버전/)
    assert.match(await page.locator('.booking-extra').textContent(),/립싱크하며 입장하시면 됩니다/)
    assert.match(await page.locator('.booking-extra').textContent(),/빠른 작업을 원하실 경우 선택해 주세요/)
    assert.equal(await page.locator('#reservationDate,#contactTime').count(),0)
    assert.match(await page.locator('.booking-availability').textContent(),/매주 목요일부터 일요일까지만 예약 가능/)
    assert.equal(await page.getByText('참여 가능한 이벤트').count(),0)
    assert.equal(await page.locator('.event-benefits h2').textContent(),'이벤트 혜택')
    assert.ok((await page.locator('.package-list li').first().textContent()).startsWith('# '),'included work is presented as compact hashtags')
    assert.match(await page.locator('.package-list').textContent(),/협업 촬영 스튜디오 대여/)
   }
   const overflow=await page.evaluate(()=>({viewport:innerWidth,body:document.documentElement.scrollWidth,bad:[...document.querySelectorAll('main *')].filter(e=>e.getBoundingClientRect().right>innerWidth+2&&getComputedStyle(e).position!=='fixed').slice(0,4).map(e=>e.className)}))
   assert.ok(overflow.body<=width+1,JSON.stringify({width,route,...overflow}))
   if(route.startsWith('/detail/')||route.startsWith('/ar/')){
    await page.evaluate(()=>scrollTo(0,document.body.scrollHeight/2))
    const rect=await page.locator('.fixed-price').boundingBox()
    assert.ok(rect.y+rect.height<=page.viewportSize().height+1,'fixed CTA '+route)
    assert.equal(await page.locator('.fixed-price a').count(),1)
   }
   report.checks.push(width+'px '+route)
  }
  await page.evaluate(()=>location.hash='#/')
  await page.waitForTimeout(100)
  await page.evaluate(async()=>{for(const img of document.querySelectorAll('img')){img.loading='eager'}await Promise.all([...document.images].map(img=>img.decode().catch(()=>{})));scrollTo(0,0)})
  await page.screenshot({path:path.join(OUT,'home-'+width+'.png'),fullPage:true})
  if(width===390||width===1440){
   await page.screenshot({path:path.join(OUT,'hero-'+width+'.png')})
   await page.evaluate(()=>location.hash='#/detail/wedding')
   await page.waitForTimeout(100)
   await page.locator('.worry-section summary').first().click()
   assert.equal(await page.locator('.worry-section details').first().getAttribute('open'),'')
   await page.locator('.reviews-section').scrollIntoViewIfNeeded()
   const reviewTrack=page.locator('#reviewTrack')
   assert.equal(await reviewTrack.locator('.review-set').count(),2,'review orbit contains two identical sets for a seamless loop')
   assert.equal(await reviewTrack.locator('.review-capture').count(),22,'all eleven reviews are duplicated for continuous motion')
   assert.equal(await page.locator('.review-carousel-controls').count(),0,'manual next and previous buttons are removed')
   await page.emulateMedia({reducedMotion:'no-preference'})
   const beforeTransform=await reviewTrack.locator('.review-loop').evaluate(el=>getComputedStyle(el).transform)
   await page.waitForTimeout(500)
   const afterTransform=await reviewTrack.locator('.review-loop').evaluate(el=>getComputedStyle(el).transform)
   assert.notEqual(afterTransform,beforeTransform,'review cards move continuously without clicks')
   await page.screenshot({path:path.join(OUT,'review-'+width+'.png')})
   await page.locator('[data-video]').first().click()
   assert.equal(await page.locator('iframe').count(),1)
   assert.match(await page.locator('iframe').getAttribute('src'),/5ZuTmQWCRJk/)
   await page.waitForTimeout(1200)
   await page.screenshot({path:path.join(OUT,'video-'+width+'.png')})
   await page.keyboard.press('Escape')
   assert.equal(await page.locator('iframe').count(),0)
   await page.locator('.composition-section').scrollIntoViewIfNeeded()
   await page.evaluate(async()=>{for(const img of document.querySelectorAll('.scene-grid img')){img.loading='eager'}await Promise.all([...document.querySelectorAll('.scene-grid img')].map(img=>img.decode().catch(()=>{})))})
   await page.screenshot({path:path.join(OUT,'composition-'+width+'.png')})
   await page.locator('.fixed-price a').click()
   await page.locator('.event-benefits').scrollIntoViewIfNeeded()
   if(width<=800){
    assert.equal(await page.locator('#bookingSummary').evaluate(el=>getComputedStyle(el).position),'static','mobile package summary remains in the document')
    assert.equal(await page.locator('.mobile-summary-label').isVisible(),true)
    assert.equal(await page.locator('.price-formula').isVisible(),false,'mobile package summary only shows the configuration and normal price')
    const fixedStrip=await page.locator('.booking-mobile-bar').boundingBox()
    assert.equal(await page.locator('.booking-mobile-bar').evaluate(el=>getComputedStyle(el).position),'fixed')
    assert.ok(Math.abs(fixedStrip.y+fixedStrip.height-page.viewportSize().height)<=1,'dark mobile price strip follows the viewport')
   }else{
    const stickyCalculator=await page.locator('#bookingSummary').boundingBox()
    assert.equal(await page.locator('#bookingSummary').evaluate(el=>getComputedStyle(el).position),'sticky')
    assert.ok(stickyCalculator.y>=0&&stickyCalculator.y<=130,'desktop price calculator remains visible while scrolling')
   }
   await page.locator('[data-event="blog"]').check()
   assert.match(await page.locator('.price-formula').textContent(),/290,000원.*30,000원.*260,000원/s)
   await page.locator('[data-option="rush"]').check()
   await page.locator('[data-option="bridal-ar"]').check()
   assert.match(await page.locator('.price-formula').textContent(),/330,000원/)
   assert.match(await page.locator('#mobilePrice').textContent(),/290,000원.*40,000원.*330,000원/s)
   await page.evaluate(()=>location.hash='#/event/solo')
   await page.waitForTimeout(100)
   assert.deepEqual(await page.locator('[data-song-option]').evaluateAll(nodes=>nodes.map(n=>n.dataset.songOption)),['lyrics','lyrics-making'])
   assert.equal(await page.locator('.song-option-card img').count(),2,'song options show lyric-video and recording-making images')
   await page.locator('[data-song-option="lyrics"]').check()
   await page.locator('[data-event="blog"]').check()
   await page.locator('#bookingRatio').selectOption('70')
   assert.match(await page.locator('.price-formula').textContent(),/130,000/)
   await page.evaluate(()=>scrollTo(0,0))
   await page.screenshot({path:path.join(OUT,'booking-'+width+'.png'),fullPage:true})
   await page.locator('#contactSource').selectOption({label:'인스타그램'})
   await page.locator('#contactName').fill('하영')
   await page.locator('#eventDate').fill('2026-12-20')
   await page.locator('#contactPurpose').selectOption({label:'축가'})
   await page.locator('#requestMessage').fill('낮은 키로 준비하고 싶어요')
   await page.evaluate(()=>{window.open=()=>({})})
   await page.locator('#consultForm button[type="submit"]').click()
   const msg=await page.evaluate(()=>consultationText())
   assert.ok(msg.includes('130,000원')&&msg.includes('70%')&&msg.includes('2026-12-20')&&msg.includes('하영')&&msg.includes('상담 시 협의')&&msg.includes('낮은 키'))
   await page.waitForFunction(()=>document.querySelector('.copy-toast')?.textContent.includes('복사'))
   await page.screenshot({path:path.join(OUT,'consult-'+width+'.png')})
   await page.evaluate(()=>location.hash='#/detail/solo')
   await page.waitForTimeout(100)
   await page.waitForSelector('.ratio-section:not(.is-loading)')
   assert.deepEqual(await page.locator('[data-ratio]').evaluateAll(nodes=>nodes.map(n=>n.dataset.ratio)),['30','50','70','100'])
   assert.deepEqual(await page.evaluate(()=>Object.entries(RATIO_SOURCES).map(([ratio,src])=>ratio+':'+src.split('/').pop()).sort()),['100:voice-100.wav','30:voice-30.wav','50:voice-50.wav','70:voice-70.wav'],'ratio player uses the four supplied original WAV files')
   assert.ok(await page.locator('#ratioAudio').evaluate(audio=>audio.seekable.length===1&&audio.seekable.end(0)>32),'prepared audio supports seeking across the full sample')
   await page.locator('#ratioAudio').evaluate(async audio=>{if(audio.readyState<1)await new Promise(resolve=>audio.addEventListener('loadedmetadata',resolve,{once:true}));audio.currentTime=12})
   await page.locator('[data-ratio="100"]').click()
   await page.waitForFunction(()=>document.querySelector('#ratioAudio')?.dataset.ratioAudio==='100'&&document.querySelector('#ratioAudio').currentTime>=11.5)
   assert.equal(await page.locator('#ratioAudio').getAttribute('data-ratio-audio'),'100')
   assert.ok(await page.locator('#ratioAudio').evaluate(audio=>audio.currentTime>=11.5),'ratio change keeps the current playback position')
   assert.equal(await page.locator('#ratioAudio').evaluate(audio=>audio.paused),false,'new ratio continues playing')
   await page.waitForTimeout(220)
   assert.equal(await page.locator('[data-ratio-audio]').evaluateAll(audios=>audios.filter(audio=>!audio.paused).length),1,'only one ratio audio plays after the fade transition')
   assert.ok(await page.locator('#ratioAudio').evaluate(audio=>audio.volume>.99),'new ratio restores the playback volume after fading')
   for(const ratio of ['30','50','70']){
    const beforeSwitch=await page.locator('#ratioAudio').evaluate(audio=>audio.currentTime)
    await page.locator('[data-ratio="'+ratio+'"]').click()
    await page.waitForFunction(expected=>document.querySelector('#ratioAudio')?.dataset.ratioAudio===expected,ratio)
    await page.waitForTimeout(220)
    assert.ok(await page.locator('#ratioAudio').evaluate((audio,start)=>audio.currentTime>=start-.15,beforeSwitch),'rapid ratio sequence keeps its playback position')
    assert.equal(await page.locator('[data-ratio-audio]').evaluateAll(audios=>audios.filter(audio=>!audio.paused).length),1,'rapid ratio sequence never leaves overlapping audio')
   }
   const continuedAt=await page.locator('#ratioAudio').evaluate(audio=>audio.currentTime)
   await page.waitForTimeout(350)
   assert.ok(await page.locator('#ratioAudio').evaluate((audio,start)=>audio.currentTime>start,continuedAt),'playback keeps advancing after ratio change')
   await page.locator('.wordmark').click()
   await page.locator('.situation-pill').first().click()
   assert.match(page.url(),/#\/detail\/wedding$/)
   await page.locator('#headerBack').click()
   await page.waitForTimeout(100)
   assert.match(page.url(),/#\/$/)
   report.checks.push(width+'px interactions passed')
  }
  await page.close()
 }
 assert.deepEqual(report.errors,[])
 assert.deepEqual(report.brokenAssets,[])
 console.log(JSON.stringify(report,null,2))
 fs.writeFileSync(path.join(OUT,'report.json'),JSON.stringify(report,null,2))
 } finally {await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1})
