const { chromium } = require(process.env.WISTIA_NODE_MODULES + '/playwright')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const OUT=process.env.WISTIA_QA_OUT || path.join(__dirname,'qa')
fs.mkdirSync(OUT,{recursive:true})
;(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'})
 const report={checks:[],errors:[],brokenAssets:[]}
 try {
 for(const width of [390,1440,320,768]){
  const page=await browser.newPage({viewport:{width,height:width===320?568:width===768?1024:width===1440?900:844},reducedMotion:'reduce'})
  page.on('pageerror',e=>report.errors.push(e.message))
  page.on('response',r=>{if(r.url().startsWith('http://127.0.0.1:4173/')&&r.status()>=400)report.brokenAssets.push(r.url())})
  await page.goto('http://127.0.0.1:4173/?v=77#/',{waitUntil:'domcontentloaded'})
  await page.locator('.situation-home').waitFor()
  await page.evaluate(()=>document.fonts.ready)
  assert.equal(await page.locator('.situation-pill').count(),6,'home contains six situation choices')
  assert.equal(await page.locator('.situation-group').count(),2,'home separates video preparation and live singing')
  assert.deepEqual(await page.locator('.situation-group h2').allTextContents(),['영상으로 준비하기','현장에서 직접 부르기 · 사전 녹음'])
  assert.match(await page.locator('.situation-group').nth(1).textContent(),/스튜디오에서 사전 녹음한 목소리/,'live singing path clearly explains advance studio recording')
  assert.equal(await page.locator('.situation-group>p').count(),2,'both home groups explain the difference')
  assert.equal(await page.locator('.situation-pill small').count(),6,'every home choice explains who it is for and how it is used')
  assert.deepEqual(await page.locator('.situation-pill').evaluateAll(nodes=>nodes.map(node=>node.getAttribute('href'))),['#/detail/wedding','#/film','#/detail/proposal','#/ar/self','#/ar/friend','#/detail/duo'])
  assert.ok(parseFloat(await page.locator('.wordmark>span').evaluate(node=>getComputedStyle(node).fontSize))<=17,'header wordmark stays compact')
  if(width<=768)assert.equal(await page.locator('.situation-group').evaluateAll(groups=>Math.abs(groups[0].getBoundingClientRect().top-groups[1].getBoundingClientRect().top)<2),true,'mobile home keeps both groups side by side')
  assert.equal(await page.locator('.home-hero,#finder,#services,main footer').count(),0,'home only contains the situation picker')
  if(width>320)assert.ok(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1),'home fits within one viewport')
  const routes=['/','/detail/wedding','/choose/wedding','/detail/wedding/live','/detail/wedding/making','/detail/duet-film','/choose/duet-film','/detail/duet-film/live','/detail/duet-film/making','/detail/solo-film','/choose/solo-film','/detail/solo-film/live','/detail/solo-film/making','/detail/proposal','/choose/proposal','/detail/proposal/live','/detail/proposal/making','/detail/solo','/detail/duo','/film','/song','/ar/self','/ar/friend','/event/wedding','/event/solo','/event/solo/friend','/event/duo','/event/duet-film','/event/solo-film','/event/proposal']
  for(const route of routes){
   await page.evaluate(hash=>location.hash='#'+hash,route)
   await page.waitForTimeout(90)
   assert.equal(await page.locator('h1').count(),1,'one h1 '+route)
   if(['/detail/duet-film','/detail/duet-film/live'].includes(route)){
    assert.equal(await page.locator('.detail-inline-video').count(),0,'duet film uses the same result-card layout as the wedding film')
    assert.equal(await page.locator('.detail-result-media[data-video]').count(),1,'duet film opens its video from the matching result card')
    assert.equal(await page.locator('.detail-typography').count(),0,'duet film no longer uses a typography placeholder')
    assert.equal(await page.locator('.selected-format-section').count(),0,'duet film detail does not repeat the selected format summary')
    assert.deepEqual(await page.locator('[data-process-panel="live"] h3').allTextContents(),['맞춤 제작 상담','1:1 보컬 디렉팅 & 구간별 녹음','축가 영상 촬영','디테일 수작업 보컬 보정','전문 엔지니어 믹싱 & 마스터링','영상 편집 & 색감 보정','최종 검수 & 완성본 전달'],'duet live detail preserves the supplied seven-step process')
   }
   if(route==='/detail/solo-film'){
    assert.equal(await page.locator('[data-process-panel="live"] h3').count(),7,'solo film uses the same complete film process')
    assert.match(await page.locator('[data-process-panel="live"] .process-duration-card').textContent(),/약 14일/)
    assert.equal(await page.locator('.song-film-cover').count(),1,'solo film hero contains a service image')
    assert.equal(await page.locator('.detail-typography').count(),0,'solo film no longer uses a typography placeholder')
   }
   if(route==='/ar/friend'){
     assert.deepEqual(await page.locator('.process-image img').evaluateAll(images=>images.map(image=>image.getAttribute('src'))),['assets/img/process/consultation.webp','assets/img/ar-process/friend/01-female.webp','assets/img/process/vocal-directing.webp','assets/img/ar-process/friend/03-female.webp','assets/img/process/melodyne-tuning.webp','assets/img/ar-process/friend/02-female.webp'],'friend AR process shows the full production workflow')
   }
    if(route==='/ar/self')assert.match(await page.locator('.process-image img').nth(3).getAttribute('src'),/03-ratio-casual\.webp$/,'self AR ratio image follows the recording steps')
   if(['/detail/proposal','/detail/proposal/live'].includes(route)){
    assert.match(await page.locator('[data-inline-youtube]').getAttribute('data-inline-youtube'),/pTBfPEWlyZU/)
    assert.equal(await page.locator('.detail-inline-video img').count(),1,'proposal YouTube video has a visible preview before playback')
    assert.equal(await page.locator('.selected-format-section').count(),0,'proposal detail does not repeat the selected format summary')
     assert.deepEqual(await page.locator('[data-process-panel="live"] h3').allTextContents(),['맞춤 제작 상담','1:1 보컬 디렉팅 & 구간별 녹음','뮤비 클립 촬영','디테일 수작업 보컬 보정','전문 엔지니어 믹싱 & 마스터링','영상 편집 & 색감 보정','최종 검수 & 완성본 전달'],'proposal follows the full seven-step film process')
     assert.equal(await page.locator('[data-process-panel="live"] .process-image img').count(),6,'proposal uses six correctly matched working images')
     assert.match(await page.locator('[data-process-panel="live"] .process-duration-line').textContent(),/제작 기간.*약 14일.*정확한 일정을 안내합니다/s)
     assert.equal(await page.locator('.proposal-process-section .process-type-note').count(),0,'proposal omits the redundant price-screen note')
     assert.equal(await page.locator('.proposal-reviews').count(),1,'proposal uses the compact review section')
     assert.equal(await page.locator('[data-process-panel="live"] .process-accordion details[open]').count(),0,'proposal keeps every production step closed at first')
     await page.locator('[data-process-panel="live"] summary[data-process-step]').nth(1).click()
     assert.equal(await page.locator('[data-process-panel="live"] .process-accordion details[open]').count(),1,'proposal keeps only the selected production step open')
     assert.equal(await page.locator('[data-process-panel="live"] .process-accordion details').nth(1).getAttribute('open'),'','proposal expands the production step that was selected')
   }
   if(['/choose/wedding','/choose/duet-film','/choose/solo-film','/choose/proposal'].includes(route)){
    assert.equal(await page.locator('.film-format-card,[data-film-format]').count(),0,'legacy choice routes now show product details rather than a format selector')
    assert.equal(await page.locator('.film-selection-notice').count(),0,'legacy film routes do not repeat a separate format-selection notice')
   }
   if(/^\/((detail|choose)\/(wedding|duet-film|solo-film|proposal))/.test(route)){
    assert.deepEqual(await page.locator('[data-process-format] strong').allTextContents(),['🎬 뮤비 클립 필름','🎙️ 녹음 메이킹 필름'],'film detail provides clearly marked process choices')
    assert.equal(await page.locator('[data-process-panel="live"]').isVisible(),true,'A type process is visible by default')
    assert.equal(await page.locator('[data-process-panel="making"]').isVisible(),false,'B type process is hidden by default')
    assert.equal(await page.locator('[data-process-format][aria-selected="true"] .process-type-marker').count(),1,'exactly one process choice is visibly selected')
   }
   if(route==='/film'){
    assert.match(await page.locator('.picker-grid article').nth(1).locator('img').getAttribute('src'),/solo-film-cover-v2\.webp/)
    assert.deepEqual(await page.locator('.picker-photo').evaluateAll(links=>links.map(link=>link.getAttribute('href'))),['#/detail/duet-film','#/detail/solo-film'],'duet film enters product details before price selection')
   }
   if(route==='/ar/friend'){
    assert.equal(await page.locator('.option-banner').count(),2,'friend AR shows lyric-video and extra-person guidance')
    assert.match(await page.locator('.fixed-price a').getAttribute('href'),/#\/event\/solo\/friend$/)
   }
   if(route==='/ar/self'){
    assert.equal(await page.locator('.process-list h3').count(),7,'AR production is explained in seven detailed steps')
    assert.equal(await page.locator('.process-image img').count(),6,'AR process uses six accurately matched working images')
    assert.equal(await page.locator('.process-duration-card').count(),1,'AR process ends with a seven-day production card')
    assert.equal(await page.locator('.process-list h3').first().textContent(),'맞춤 제작 상담 · 곡과 키 확인')
    assert.match(await page.locator('.process-list').textContent(),/녹음 준비.*보컬 디렉팅.*목소리 비율 선택.*멜로다인.*믹싱.*완성본 전달/s,'self recording process explains each production stage')
    assert.equal(await page.locator('.reviews-section').count(),1,'self AR page includes real customer reviews')
   }
   if(route==='/detail/solo'||route==='/detail/duo'){
    assert.equal(await page.locator('.ratio-section').count(),1,'every prerecorded live-song detail contains AR ratio samples')
    assert.equal(await page.locator('[data-ratio="70"] small').textContent(),'가장 인기')
    assert.equal(await page.locator('[data-ratio="100"] small').textContent(),'완전 안전')
    assert.ok((await page.locator('[data-ratio="70"]').boundingBox()).width>(await page.locator('[data-ratio="100"]').boundingBox()).width,'popular 70 percent choice is more prominent than 100 percent')
    assert.equal(await page.locator('.process-list h3').count(),7,'live-song detail uses the same detailed seven-step production flow')
    assert.match(await page.locator('.process-duration-card').textContent(),/약 7일/)
   }
   if(route==='/event/solo/friend')assert.match(await page.locator('.friend-options').textContent(),/인원 추가.*상담 후 안내/s)
   if(['/event/solo','/event/solo/friend','/event/duo'].includes(route)){
    assert.equal(await page.locator('#bookingRatio').count(),0,'booking page removes the duplicated AR ratio selector')
    assert.equal(await page.locator('.switch-products').count(),0,'booking page removes unrelated product switch buttons')
    assert.equal(await page.locator('#mobilePrice del').count(),0,'normal price is not crossed out before an event discount is selected')
   }
   if(['/event/wedding','/event/duet-film','/event/solo-film','/event/proposal'].includes(route)){
    assert.equal(await page.locator('[data-film-format]').count(),2,'each film booking page provides both format choices')
    if(route!='/event/proposal'){
     assert.deepEqual(await page.locator('.booking-format-card strong').allTextContents(),['뮤비 클립 필름','녹음 메이킹 필름'])
     assert.ok(await page.locator('.booking-format-media img').count()>=2,'format choices show their real example images in the price page')
    }
    assert.equal(await page.locator('.package-section').getAttribute('open'),null,'type-specific included work starts collapsed')
   }
   if(route==='/event/proposal'){
    assert.equal(await page.locator('.booking-format-toggle').count(),1,'proposal uses a compact format toggle')
    assert.equal(await page.locator('.booking-format-card').count(),0,'proposal removes the large side-by-side format cards')
    assert.equal(await page.locator('.proposal-format-selector > #bookingSummary').count(),1,'proposal places the price table directly below the format choice')
    await page.locator('.booking-format-toggle label').nth(1).click()
    assert.match(await page.locator('[data-proposal-format-preview]').textContent(),/녹음 메이킹 필름.*인서트 컷/s)
   }
   if(route==='/event/duet-film'){
    assert.deepEqual(await page.locator('.booking-format-card').nth(1).locator('.booking-format-media img').evaluateAll(images=>images.map(image=>image.getAttribute('src'))),['assets/img/duet-film/making-female.webp','assets/img/duet-film/making-male.webp'],'duet recording-making option uses both supplied recording photos')
   }
   if(['/detail/wedding','/detail/wedding/live'].includes(route)){
    const ordered=await page.locator('#process,.worry-section,.reviews-section,.detail-next').evaluateAll(nodes=>nodes.map(n=>n.className||n.id))
    assert.deepEqual(ordered,['shell section film-process-section','section reviews-section','shell section worry-section','detail-next section'],'reviews appear above frequently asked questions')
    assert.equal(await page.locator('.detail-intro,.result-band,.expertise').count(),0,'repeated intro, result and expertise sections are removed')
    assert.equal(await page.locator('.selected-format-section').count(),0,'selected format summary is not repeated inside its detail page')
    assert.equal(await page.locator('[data-inline-youtube]').count(),1,'wedding result shows a playable YouTube preview without a popup')
    assert.match(await page.locator('.detail-inline-video img').getAttribute('src'),/wedding\/03-lipsync-mv\.webp$/,'YouTube area never appears as an empty black block')
    assert.equal(await page.getByRole('link',{name:/듀엣 웨딩 필름 레퍼런스 보기/}).count(),0,'the redundant wedding reference link is removed')
    assert.deepEqual(await page.locator('[data-process-panel="live"] h3').allTextContents(),['맞춤 제작 상담','1:1 보컬 디렉팅 & 구간별 녹음','스토리 영상 촬영','디테일 수작업 보컬 보정','전문 엔지니어 믹싱 & 마스터링','영상 편집 & 색감 보정','최종 검수 & 완성본 전달'],'wedding live detail preserves the supplied seven-step process')
    assert.equal(await page.locator('[data-process-panel="live"] .process-image img').count(),6,'wedding process uses six accurately matched images')
    assert.match(await page.locator('[data-process-panel="live"] .process-duration-card').textContent(),/약 14일/)
    assert.equal(await page.locator('.detail-facts b').count(),2,'detail facts have clear labels')
    assert.equal(await page.locator('.production-guide').count(),0,'production guide is removed')
    assert.equal(await page.locator('.review-capture:not([aria-hidden]) img').count(),11,'all real review captures are available in the carousel')
    assert.equal(await page.getByText(/모두 보기|11개/).count(),0,'review count and show-all link are removed')
    assert.equal(await page.locator('.detail-price-section,.booking-layout').count(),0,'detail page stops before package and reservation')
    assert.equal(await page.locator('.film-format-card').count(),0,'selected detail no longer embeds the two-choice screen')
    assert.equal(await page.locator('.film-selection-notice').count(),0,'the separate film-selection notice is removed')
    assert.deepEqual(await page.locator('.worry-section summary').allTextContents(),['뮤비 클립 필름과 녹음 메이킹 필름은 무엇이 다른가요+','녹음과 촬영은 같은 날 진행되나요+','준비해야 할 사진이나 문구가 있나요+','완성까지 얼마나 걸리나요+','예식장에서 바로 상영할 수 있는 파일로 받을 수 있나요+'],'wedding FAQ contains only practical production questions')
    assert.doesNotMatch(await page.locator('.worry-section').textContent(),/둘만의 특별한 추억을 남기고 싶어요|직접 부르기에는 부담스러워요|둘 다 노래를 잘 못해도 괜찮나요/,'wedding FAQ does not repeat customer concerns')
    assert.match(await page.locator('.fixed-price a').getAttribute('href'),/#\/event\/wedding$/)
   }
   if(['/detail/wedding/making','/detail/duet-film/making','/detail/proposal/making'].includes(route)){
    assert.equal(await page.locator('.selected-format-section').count(),0,'making detail does not repeat the selected format summary')
    assert.equal(await page.locator('.film-format-card,[data-film-format]').count(),0,'format selection only appears on the price page')
    assert.equal(await page.locator('.film-selection-notice').count(),0,'making detail does not repeat a separate selection notice')
    assert.match(await page.locator('.fixed-price a').getAttribute('href'),/\/event\/[^/]+$/)
   }
   if(route==='/event/wedding'){
    assert.equal(await page.locator('.booking-layout').count(),1,'price page contains package and reservation')
    assert.equal(await page.locator('[data-film-format]').count(),2,'film price page provides two real radio choices')
    assert.equal(await page.locator('[data-film-format="live"]').isChecked(),true,'live clip is the default choice')
    assert.equal(await page.locator('.booking-extra .option-choice').count(),2,'wedding price page contains two selectable additional options')
    assert.equal(await page.locator('.booking-extra .option-notice').count(),1,'additional revision is information only')
    assert.match(await page.locator('.booking-extra').textContent(),/3일 이내 빠른 작업/)
    assert.match(await page.locator('.booking-extra').textContent(),/기본 수정 3회까지 무료/)
    assert.match(await page.locator('.booking-extra').textContent(),/신부 입장곡 AR · 립싱크 버전/)
    assert.match(await page.locator('.booking-extra').textContent(),/립싱크하며 입장하시면 됩니다/)
    assert.match(await page.locator('.booking-extra').textContent(),/빠른 작업을 원하실 경우 선택해 주세요/)
    assert.equal(await page.locator('#reservationDate,#contactTime').count(),0)
    assert.match(await page.locator('.booking-availability').textContent(),/목요일부터 일요일까지 예약 가능/)
    assert.equal(await page.locator('#requestMessage,#contactService').count(),0,'the compact checkout removes extra inquiry and repeated service fields')
    assert.equal(await page.locator('.booking-checkout #bookingSummary + .event-benefits + #consultForm').count(),1,'event discounts sit directly below the calculator inside one checkout panel')
    assert.equal(await page.getByText('참여 가능한 이벤트').count(),0)
     assert.match(await page.locator('.event-benefits summary').textContent(),/이벤트 적용가도 확인하기.*얼마나 싸질까/s)
     assert.equal(await page.locator('.event-benefits').getAttribute('open'),null,'event prices are tucked into a disclosure by default')
     assert.match(await page.locator('.package-section summary').textContent(),/뮤비 클립 필름 기본 구성/)
     assert.equal(await page.locator('.package-list li>span:first-child').first().textContent(),'✓','included work is presented as a clear checked list')
     assert.match(await page.locator('.package-list').textContent(),/하객 메시지 촬영.*인터뷰 촬영.*뮤비 클립 촬영.*전하는 편지 촬영/s)
     assert.deepEqual(await page.locator('.booking-format-price').allTextContents(),['300,000원','250,000원'],'wedding film formats display distinct temporary prices')
   }
   const overflow=await page.evaluate(()=>({viewport:innerWidth,body:document.documentElement.scrollWidth,bad:[...document.querySelectorAll('main *')].filter(e=>e.getBoundingClientRect().right>innerWidth+2&&getComputedStyle(e).position!=='fixed').slice(0,4).map(e=>e.className)}))
   assert.ok(overflow.body<=width+1,JSON.stringify({width,route,...overflow}))
   if(route.startsWith('/detail/')||route.startsWith('/ar/')){
    await page.evaluate(()=>scrollTo(0,document.body.scrollHeight/2))
    const rect=await page.locator('.fixed-price').boundingBox()
    assert.ok(rect.y+rect.height<=page.viewportSize().height+1,'fixed CTA '+route)
    assert.equal(await page.locator('.fixed-price a').count(),1)
   }
   if(route.startsWith('/detail/')){
    const order=await page.locator('.reviews-section,.worry-section').evaluateAll(nodes=>nodes.map(node=>node.classList.contains('reviews-section')?'reviews':'faq'))
    assert.deepEqual(order,['reviews','faq'],'customer reviews precede FAQ on every detail page')
   }
   report.checks.push(width+'px '+route)
  }
  await page.evaluate(()=>location.hash='#/')
  await page.waitForTimeout(100)
  await page.evaluate(async()=>{for(const img of document.querySelectorAll('img')){img.loading='eager'}await Promise.all([...document.images].map(img=>img.decode().catch(()=>{})));scrollTo(0,0)})
  await page.screenshot({path:path.join(OUT,'home-'+width+'.png'),fullPage:true})
  if(width===390||width===1440){
   await page.screenshot({path:path.join(OUT,'hero-'+width+'.png')})
   await page.evaluate(()=>location.hash='#/detail/wedding')
   await page.waitForTimeout(100)
   await page.locator('.worry-section summary').first().click()
   assert.equal(await page.locator('.worry-section details').first().getAttribute('open'),'')
   await page.locator('.reviews-section').scrollIntoViewIfNeeded()
   const reviewTrack=page.locator('#reviewTrack')
   assert.equal(await reviewTrack.locator('.review-set').count(),2,'review orbit contains two identical sets for a seamless loop')
   assert.equal(await reviewTrack.locator('.review-capture').count(),22,'all eleven reviews are duplicated for continuous motion')
   assert.equal(await page.locator('.review-carousel-controls button').count(),2,'review carousel includes previous and next buttons')
   const beforeTransform=await reviewTrack.locator('.review-loop').evaluate(el=>getComputedStyle(el).transform)
   await page.locator('[data-review-next]').click()
   await page.waitForTimeout(700)
   const afterTransform=await reviewTrack.locator('.review-loop').evaluate(el=>getComputedStyle(el).transform)
   assert.notEqual(afterTransform,beforeTransform,'review cards move with the next control')
   await page.screenshot({path:path.join(OUT,'review-'+width+'.png')})
   assert.equal(await page.locator('[data-video]').count(),0,'wedding video does not open a popup')
   await page.locator('[data-inline-youtube]').click()
   assert.match(await page.locator('.detail-inline-video iframe').getAttribute('src'),/5ZuTmQWCRJk/)
   assert.match(await page.locator('.detail-inline-video iframe').getAttribute('src'),/autoplay=1/)
   await page.screenshot({path:path.join(OUT,'video-'+width+'.png')})
   await page.evaluate(()=>location.hash='#/detail/wedding')
   await page.waitForTimeout(100)
   await page.locator('#process').scrollIntoViewIfNeeded()
   await page.evaluate(async()=>{for(const img of document.querySelectorAll('#process img')){img.loading='eager'}await Promise.all([...document.querySelectorAll('#process img')].map(img=>img.decode().catch(()=>{})))})
   await page.screenshot({path:path.join(OUT,'composition-'+width+'.png')})
   await page.locator('[data-process-format="making"]').click()
   assert.equal(await page.locator('[data-process-panel="live"]').isVisible(),false,'A type process hides after selecting B type')
   assert.equal(await page.locator('[data-process-panel="making"]').isVisible(),true,'B type recording-making process appears')
   assert.match(await page.locator('[data-process-panel="making"]').textContent(),/녹음 메이킹 영상 촬영.*인서트 컷.*인트로·아웃트로/s)
   assert.deepEqual(await page.locator('[data-process-panel="making"] .process-image img').evaluateAll(images=>images.slice(-2).map(image=>image.getAttribute('src'))),['assets/img/ar-process/02-mixing.webp','assets/img/process/video-color-grading.webp'],'recording-making process ends with mixing and video color grading')
   assert.equal(await page.locator('.film-format-card,[data-film-format]').count(),0,'detail page explains format selection without displaying the selector')
   await page.locator('.fixed-price a').click()
   assert.match(page.url(),/#\/event\/wedding$/)
   await page.locator('.booking-film-format').scrollIntoViewIfNeeded()
   const beforeFormatY=await page.evaluate(()=>scrollY)
   await page.locator('[data-film-format="making"]').evaluate(input=>input.click())
   await page.waitForTimeout(80)
   assert.ok(Math.abs((await page.evaluate(()=>scrollY))-beforeFormatY)<=1,'changing the film format preserves the current scroll position')
   assert.equal(await page.locator('[data-film-format="making"]').isChecked(),true,'selected detail format carries into booking')
   assert.equal(await page.locator('.package-section').getAttribute('open'),'','selected type details open directly below the selector')
   assert.match(await page.locator('[data-package-title]').textContent(),/녹음 메이킹 필름 기본 구성/)
   assert.match(await page.locator('#bookingSummary').textContent(),/영상 구성.*녹음 메이킹 필름/s)
   assert.match(await page.locator('.package-list').textContent(),/인서트 컷 촬영.*녹음실 메이킹 촬영.*인트로·아웃트로 타이포/s)
   assert.doesNotMatch(await page.locator('.package-list').textContent(),/인터뷰 촬영|전하는 편지 촬영/)
   await page.locator('.event-benefits').scrollIntoViewIfNeeded()
   await page.locator('.event-benefits summary').click()
   if(width<=800){
    assert.equal(await page.locator('#bookingSummary').evaluate(el=>getComputedStyle(el).position),'static','mobile package summary remains in the document')
    assert.equal(await page.locator('.mobile-summary-label').isVisible(),true)
    assert.equal(await page.locator('.price-formula').isVisible(),true,'mobile combined checkout keeps the full price calculator visible')
    const fixedStrip=await page.locator('.booking-mobile-bar').boundingBox()
    assert.equal(await page.locator('.booking-mobile-bar').evaluate(el=>getComputedStyle(el).position),'fixed')
    assert.ok(Math.abs(fixedStrip.y+fixedStrip.height-page.viewportSize().height)<=1,'dark mobile price strip follows the viewport')
   }else{
    assert.equal(await page.locator('.booking-checkout').evaluate(el=>getComputedStyle(el).position),'sticky','combined desktop checkout follows the viewport')
   }
   await page.locator('[data-event="blog"]').check()
   assert.equal(await page.locator('#mobilePrice del').count(),1,'normal price is crossed out only after an event discount is selected')
   assert.match(await page.locator('.price-formula').textContent(),/250,000원.*30,000원.*220,000원/s)
   await page.locator('[data-option="rush"]').check()
   await page.locator('[data-option="bridal-ar"]').check()
   assert.match(await page.locator('.price-formula').textContent(),/290,000원/)
   assert.match(await page.locator('#mobilePrice').textContent(),/250,000원.*40,000원.*290,000원/s)
   const formatMsg=await page.evaluate(()=>consultationText())
   assert.match(formatMsg,/선택한 영상 구성 : 녹음 메이킹 필름/)
   await page.evaluate(()=>location.hash='#/event/solo')
   await page.waitForTimeout(100)
   assert.deepEqual(await page.locator('[data-song-option]').evaluateAll(nodes=>nodes.map(n=>n.dataset.songOption)),['lyrics','lyrics-making'])
   assert.equal(await page.locator('.song-option-card img').count(),2,'song options show lyric-video and recording-making images')
   await page.locator('[data-song-option="lyrics"]').check()
   await page.locator('.event-benefits summary').click()
   await page.locator('[data-event="blog"]').check()
   assert.match(await page.locator('.price-formula').textContent(),/130,000/)
   await page.evaluate(()=>scrollTo(0,0))
   await page.screenshot({path:path.join(OUT,'booking-'+width+'.png'),fullPage:true})
   await page.locator('#contactSource').selectOption({label:'인스타그램'})
   await page.locator('#contactName').fill('하영')
   await page.locator('#eventDate').fill('2026-12-20')
   await page.locator('#contactPurpose').selectOption({label:'축가'})
   await page.evaluate(()=>{window.open=()=>({})})
   await (width<=800?page.locator('.booking-mobile-bar button[type="submit"]'):page.locator('#consultForm button[type="submit"]')).click()
   const msg=await page.evaluate(()=>consultationText())
   assert.ok(msg.includes('130,000원')&&msg.includes('2026-12-20')&&msg.includes('하영')&&msg.includes('상담 시 협의'))
   assert.doesNotMatch(msg,/AR 목소리 비율/)
   assert.doesNotMatch(msg,/추가 문의/)
   await page.waitForFunction(()=>document.querySelector('.copy-toast')?.textContent.includes('복사'))
   await page.screenshot({path:path.join(OUT,'consult-'+width+'.png')})
   await page.evaluate(()=>location.hash='#/detail/solo')
   await page.waitForTimeout(100)
   await page.waitForSelector('.ratio-section:not(.is-loading)')
   assert.deepEqual(await page.locator('[data-ratio]').evaluateAll(nodes=>nodes.map(n=>n.dataset.ratio)),['30','50','70','100'])
   assert.equal(await page.locator('[data-ratio-audio]').count(),1,'ratio selector uses one stable audio player')
   assert.match(await page.locator('.ratio-guide').textContent(),/70%와 100%.*완전한 립싱크.*마이크를 꺼/s,'ratio guide explains the popular choices and 100% lip sync')
   assert.deepEqual(await page.evaluate(()=>Object.entries(RATIO_SOURCES).map(([ratio,src])=>ratio+':'+src.split('/').pop()).sort()),['100:voice-100.wav','30:voice-30.wav','50:voice-50.wav','70:voice-70.wav'],'ratio player uses the four supplied original WAV files')
   assert.ok(await page.locator('#ratioAudio').evaluate(audio=>audio.seekable.length===1&&audio.seekable.end(0)>32),'prepared audio supports seeking across the full sample')
   await page.locator('#ratioAudio').evaluate(async audio=>{if(audio.readyState<1)await new Promise(resolve=>audio.addEventListener('loadedmetadata',resolve,{once:true}));audio.currentTime=12})
   await page.locator('[data-ratio="100"]').click()
   await page.waitForFunction(()=>document.querySelector('#ratioAudio')?.dataset.ratioAudio==='100'&&document.querySelector('#ratioAudio').currentTime>=11.5)
   assert.equal(await page.locator('#ratioAudio').getAttribute('data-ratio-audio'),'100')
   assert.ok(await page.locator('#ratioAudio').evaluate(audio=>audio.currentTime>=11.5),'ratio change keeps the current playback position')
   assert.equal(await page.locator('#ratioAudio').evaluate(audio=>audio.paused),false,'new ratio continues playing')
   await page.waitForTimeout(220)
   assert.equal(await page.locator('[data-ratio-audio]').evaluateAll(audios=>audios.filter(audio=>!audio.paused).length),1,'only one ratio audio plays after the fade transition')
   assert.ok(await page.locator('#ratioAudio').evaluate(audio=>audio.volume>.99),'new ratio restores the playback volume after fading')
   for(const ratio of ['30','50','70']){
    const beforeSwitch=await page.locator('#ratioAudio').evaluate(audio=>audio.currentTime)
    await page.locator('[data-ratio="'+ratio+'"]').click()
    await page.waitForFunction(expected=>document.querySelector('#ratioAudio')?.dataset.ratioAudio===expected,ratio)
    await page.waitForTimeout(220)
    assert.ok(await page.locator('#ratioAudio').evaluate((audio,start)=>audio.currentTime>=start-.15,beforeSwitch),'rapid ratio sequence keeps its playback position')
    assert.equal(await page.locator('[data-ratio-audio]').evaluateAll(audios=>audios.filter(audio=>!audio.paused).length),1,'rapid ratio sequence never leaves overlapping audio')
   }
   const continuedAt=await page.locator('#ratioAudio').evaluate(audio=>audio.currentTime)
   await page.waitForTimeout(350)
   assert.ok(await page.locator('#ratioAudio').evaluate((audio,start)=>audio.currentTime>start,continuedAt),'playback keeps advancing after ratio change')
   await page.locator('.wordmark').click()
   await page.locator('.situation-pill').first().click()
   assert.match(page.url(),/#\/detail\/wedding$/)
   await page.locator('#headerBack').click()
   await page.waitForTimeout(100)
   assert.match(page.url(),/#\/$/)
   report.checks.push(width+'px interactions passed')
  }
  await page.close()
 }
 const motionPage=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'no-preference'})
 await motionPage.goto('http://127.0.0.1:4173/?v=89#/detail/duo',{waitUntil:'domcontentloaded'})
 await motionPage.locator('.review-loop').waitFor()
 await motionPage.waitForTimeout(350)
 const motionStart=await motionPage.locator('.review-loop').evaluate(el=>getComputedStyle(el).transform)
 await motionPage.waitForTimeout(600)
 const motionEnd=await motionPage.locator('.review-loop').evaluate(el=>getComputedStyle(el).transform)
 assert.notEqual(motionEnd,motionStart,'reviews move continuously without a rigid timed jump')
 assert.match(await motionPage.locator('.review-crop-06 img').first().getAttribute('src'),/review-06-clean\.webp$/,'review six uses the clean crop without the captured Instagram arrow')
 await motionPage.close()
 assert.deepEqual(report.errors,[])
 assert.deepEqual(report.brokenAssets,[])
 console.log(JSON.stringify(report,null,2))
 fs.writeFileSync(path.join(OUT,'report.json'),JSON.stringify(report,null,2))
 } finally {await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1})
