const { chromium } = require(process.env.WISTIA_NODE_MODULES + '/playwright')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const OUT=process.env.WISTIA_QA_OUT || path.join(__dirname,'qa')
fs.mkdirSync(OUT,{recursive:true})
;(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'})
 const report={checks:[],errors:[],brokenAssets:[]}
 try {
 for(const width of [390,1440,320,768]){
  const page=await browser.newPage({viewport:{width,height:width===320?568:width===768?1024:width===1440?900:844},reducedMotion:'reduce'})
  page.on('pageerror',e=>report.errors.push(e.message))
  page.on('response',r=>{if(r.url().startsWith('http://127.0.0.1:4173/')&&r.status()>=400)report.brokenAssets.push(r.url())})
  await page.goto('http://127.0.0.1:4173/?v=77#/',{waitUntil:'domcontentloaded'})
  await page.locator('.situation-home').waitFor()
  await page.evaluate(()=>document.fonts.ready)
  assert.equal(await page.locator('.situation-pill').count(),6,'home contains six situation choices')
  assert.equal(await page.locator('.situation-group').count(),2,'home separates video preparation and live singing')
  assert.deepEqual(await page.locator('.situation-group h2').allTextContents(),['영상으로 준비하기','현장에서 직접 부르기 · 사전 녹음'])
  assert.match(await page.locator('.situation-group').nth(1).textContent(),/스튜디오에서 사전 녹음한 목소리/,'live singing path clearly explains advance studio recording')
  assert.equal(await page.locator('.situation-group>p').count(),2,'both home groups explain the difference')
  assert.equal(await page.locator('.situation-pill small').count(),6,'every home choice explains who it is for and how it is used')
  assert.deepEqual(await page.locator('.situation-pill').evaluateAll(nodes=>nodes.map(node=>node.getAttribute('href'))),['#/choose/wedding','#/film','#/choose/proposal','#/ar/self','#/ar/friend','#/detail/duo'])
  assert.ok(parseFloat(await page.locator('.wordmark>span').evaluate(node=>getComputedStyle(node).fontSize))<=17,'header wordmark stays compact')
  if(width<=768)assert.equal(await page.locator('.situation-group').evaluateAll(groups=>Math.abs(groups[0].getBoundingClientRect().top-groups[1].getBoundingClientRect().top)<2),true,'mobile home keeps both groups side by side')
  assert.equal(await page.locator('.home-hero,#finder,#services,main footer').count(),0,'home only contains the situation picker')
  if(width>320)assert.ok(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1),'home fits within one viewport')
  const routes=['/','/choose/wedding','/detail/wedding/live','/detail/wedding/making','/choose/duet-film','/detail/duet-film/live','/detail/duet-film/making','/detail/solo-film','/choose/proposal','/detail/proposal/live','/detail/proposal/making','/detail/solo','/detail/duo','/film','/song','/ar/self','/ar/friend','/event/wedding','/event/solo','/event/solo/friend','/event/duo','/event/duet-film','/event/solo-film','/event/proposal']
  for(const route of routes){
   await page.evaluate(hash=>location.hash='#'+hash,route)
   await page.waitForTimeout(90)
   assert.equal(await page.locator('h1').count(),1,'one h1 '+route)
   if(route==='/detail/duet-film/live'){
    assert.equal(await page.locator('.detail-inline-video').count(),0,'duet film uses the same result-card layout as the wedding film')
    assert.equal(await page.locator('.detail-result-media[data-video]').count(),1,'duet film opens its video from the matching result card')
    assert.equal(await page.locator('.detail-typography').count(),0,'duet film no longer uses a typography placeholder')
    assert.equal(await page.locator('.selected-format-section').count(),0,'duet film detail does not repeat the selected format summary')
    assert.deepEqual(await page.locator('#process h3').allTextContents(),['맞춤 제작 상담','1:1 보컬 디렉팅 & 구간별 녹음','축가 영상 촬영','디테일 수작업 보컬 보정','전문 엔지니어 믹싱 & 마스터링','영상 편집 & 색감 보정','최종 검수 & 완성본 전달'],'duet live detail preserves the supplied seven-step process')
   }
   if(route==='/detail/solo-film'){
    assert.equal(await page.locator('.scene-grid img').count(),1,'solo film base composition is recording making film only')
    assert.equal(await page.locator('.song-film-cover').count(),1,'solo film hero contains a service image')
    assert.equal(await page.locator('.detail-typography').count(),0,'solo film no longer uses a typography placeholder')
   }
   if(route==='/ar/friend'){
    assert.deepEqual(await page.locator('.process-image img').evaluateAll(images=>images.map(image=>image.getAttribute('src'))),['assets/img/ar-process/friend/01-female.webp','assets/img/ar-process/friend/02-female.webp','assets/img/ar-process/friend/03-female.webp','assets/img/ar-process/friend/04-female-live.webp'],'friend AR process uses a consistent female point of view and an obvious live singing scene')
   }
   if(route==='/ar/self')assert.match(await page.locator('.process-image img').nth(2).getAttribute('src'),/03-ratio-casual\.webp$/,'self AR ratio image uses casual clothes')
   if(route==='/detail/proposal/live'){
    assert.match(await page.locator('.detail-inline-video iframe').getAttribute('src'),/pTBfPEWlyZU/)
    assert.equal(await page.locator('.selected-format-section').count(),0,'proposal detail does not repeat the selected format summary')
    assert.deepEqual(await page.locator('#process h3').allTextContents(),['상담 · 곡 선정','1대1 녹음 디렉팅','인터뷰 촬영','편지 영상 촬영','보컬 보정 · 영상 편집'],'proposal live detail keeps its full product process')
   }
   if(['/choose/wedding','/choose/duet-film','/choose/proposal'].includes(route)){
    assert.deepEqual(await page.locator('.film-format-card h3').allTextContents(),['뮤비 라이브 클립','녹음 메이킹 클립'])
    assert.equal(await page.locator('.film-format-card').count(),2,'film product offers two selectable formats')
    assert.match(await page.locator('.film-format-card').nth(0).textContent(),/하객 메시지.*인터뷰.*라이브 뮤비 클립.*서로에게 전하는 편지/s)
    assert.match(await page.locator('.film-format-card').nth(1).textContent(),/인서트 컷.*녹음실 메이킹 컷.*인터뷰와 전하는 편지 촬영은 기본 구성에서 제외.*타이포.*직접 집이나 방에서 촬영.*인터뷰 촬영은 진행되지 않습니다/s)
   }
   if(route==='/film'){
    assert.match(await page.locator('.picker-grid article').nth(1).locator('img').getAttribute('src'),/solo-film-cover-v2\.webp/)
    assert.deepEqual(await page.locator('.picker-photo').evaluateAll(links=>links.map(link=>link.getAttribute('href'))),['#/choose/duet-film','#/detail/solo-film'],'duet film enters format choice before product details')
   }
   if(route==='/ar/friend'){
    assert.equal(await page.locator('.option-banner').count(),2,'friend AR shows lyric-video and extra-person guidance')
    assert.match(await page.locator('.fixed-price a').getAttribute('href'),/#\/event\/solo\/friend$/)
   }
   if(route==='/ar/self'){
    assert.equal(await page.locator('.process-image img').count(),4,'AR process uses four illustrated steps')
    assert.equal(await page.locator('.process-list h3').first().textContent(),'스튜디오 방문 · 축가 사전 녹음')
    assert.match(await page.locator('.process-list li').first().textContent(),/위스티아 스튜디오.*엔지니어.*1:1 디렉팅.*한 소절씩/s,'self recording process explains the studio visit in detail')
    assert.equal(await page.locator('.reviews-section').count(),1,'self AR page includes real customer reviews')
   }
   if(route==='/detail/solo'||route==='/detail/duo')assert.equal(await page.locator('.ratio-section').count(),1,'every prerecorded live-song detail contains AR ratio samples')
   if(route==='/event/solo/friend')assert.match(await page.locator('.friend-options').textContent(),/인원 추가.*상담 후 안내/s)
   if(['/event/wedding','/event/duet-film','/event/proposal'].includes(route)){
    assert.deepEqual(await page.locator('.booking-format-card strong').allTextContents(),['뮤비 라이브 클립','녹음 메이킹 클립'])
    assert.equal(await page.locator('[data-film-format]').count(),2,'each film booking page provides both format choices')
   }
   if(route==='/detail/wedding/live'){
    const ordered=await page.locator('#process,.worry-section,.reviews-section,.detail-next').evaluateAll(nodes=>nodes.map(n=>n.className||n.id))
    assert.deepEqual(ordered,['shell section','shell section worry-section','section reviews-section','detail-next section'],'the full production process sits directly below the result video')
    assert.equal(await page.locator('.detail-intro,.result-band,.expertise').count(),0,'repeated intro, result and expertise sections are removed')
    assert.equal(await page.locator('.selected-format-section').count(),0,'selected format summary is not repeated inside its detail page')
    assert.equal(await page.locator('.detail-inline-video iframe').count(),1,'wedding result plays inline without a popup')
    const reference=page.getByRole('link',{name:/듀엣 웨딩 필름 레퍼런스 보기/})
    assert.match(await reference.getAttribute('href'),/youtube\.com\/watch\?v=5ZuTmQWCRJk/)
    assert.equal(await reference.getAttribute('target'),'_blank')
    assert.deepEqual(await page.locator('#process h3').allTextContents(),['맞춤 제작 상담','1:1 보컬 디렉팅 & 구간별 녹음','스토리 영상 촬영','디테일 수작업 보컬 보정','전문 엔지니어 믹싱 & 마스터링','영상 편집 & 색감 보정','최종 검수 & 완성본 전달'],'wedding live detail preserves the supplied seven-step process')
    assert.equal(await page.locator('.detail-facts b').count(),2,'detail facts have clear labels')
    assert.equal(await page.locator('.production-guide').count(),0,'production guide is removed')
    assert.equal(await page.locator('.review-capture:not([aria-hidden]) img').count(),11,'all real review captures are available in the carousel')
    assert.equal(await page.getByText(/모두 보기|11개/).count(),0,'review count and show-all link are removed')
    assert.equal(await page.locator('.detail-price-section,.booking-layout').count(),0,'detail page stops before package and reservation')
    assert.equal(await page.locator('.film-format-card').count(),0,'selected detail no longer embeds the two-choice screen')
    assert.match(await page.locator('.fixed-price a').getAttribute('href'),/#\/event\/wedding\/live$/)
   }
   if(['/detail/wedding/making','/detail/duet-film/making','/detail/proposal/making'].includes(route)){
    assert.equal(await page.locator('.selected-format-section').count(),0,'making detail does not repeat the selected format summary')
    assert.equal(await page.locator('.film-format-card').count(),0,'making detail shows only its selected format')
    assert.match(await page.locator('#process').textContent(),/녹음 메이킹 영상 촬영.*인서트 컷.*녹음실 메이킹 컷/s)
    assert.match(await page.locator('.fixed-price a').getAttribute('href'),/\/event\/[^/]+\/making$/)
   }
   if(route==='/event/wedding'){
    assert.equal(await page.locator('.booking-layout').count(),1,'price page contains package and reservation')
    assert.equal(await page.locator('[data-film-format]').count(),2,'film price page provides two real radio choices')
    assert.equal(await page.locator('[data-film-format="live"]').isChecked(),true,'live clip is the default choice')
    assert.equal(await page.locator('.booking-extra .option-choice').count(),2,'wedding price page contains two selectable additional options')
    assert.equal(await page.locator('.booking-extra .option-notice').count(),1,'additional revision is information only')
    assert.match(await page.locator('.booking-extra').textContent(),/3일 이내 빠른 작업/)
    assert.match(await page.locator('.booking-extra').textContent(),/기본 수정 3회까지 무료/)
    assert.match(await page.locator('.booking-extra').textContent(),/신부 입장곡 AR · 립싱크 버전/)
    assert.match(await page.locator('.booking-extra').textContent(),/립싱크하며 입장하시면 됩니다/)
    assert.match(await page.locator('.booking-extra').textContent(),/빠른 작업을 원하실 경우 선택해 주세요/)
    assert.equal(await page.locator('#reservationDate,#contactTime').count(),0)
    assert.match(await page.locator('.booking-availability').textContent(),/매주 목요일부터 일요일까지만 예약 가능/)
    assert.equal(await page.getByText('참여 가능한 이벤트').count(),0)
    assert.equal(await page.locator('.event-benefits h2').textContent(),'이벤트 혜택')
    assert.ok((await page.locator('.package-list li').first().textContent()).startsWith('# '),'included work is presented as compact hashtags')
    assert.match(await page.locator('.package-list').textContent(),/하객 메시지 촬영.*인터뷰 촬영.*라이브 뮤비 클립 촬영.*서로에게 전하는 편지 촬영/s)
   }
   const overflow=await page.evaluate(()=>({viewport:innerWidth,body:document.documentElement.scrollWidth,bad:[...document.querySelectorAll('main *')].filter(e=>e.getBoundingClientRect().right>innerWidth+2&&getComputedStyle(e).position!=='fixed').slice(0,4).map(e=>e.className)}))
   assert.ok(overflow.body<=width+1,JSON.stringify({width,route,...overflow}))
   if(route.startsWith('/detail/')||route.startsWith('/ar/')){
    await page.evaluate(()=>scrollTo(0,document.body.scrollHeight/2))
    const rect=await page.locator('.fixed-price').boundingBox()
    assert.ok(rect.y+rect.height<=page.viewportSize().height+1,'fixed CTA '+route)
    assert.equal(await page.locator('.fixed-price a').count(),1)
   }
   report.checks.push(width+'px '+route)
  }
  await page.evaluate(()=>location.hash='#/')
  await page.waitForTimeout(100)
  await page.evaluate(async()=>{for(const img of document.querySelectorAll('img')){img.loading='eager'}await Promise.all([...document.images].map(img=>img.decode().catch(()=>{})));scrollTo(0,0)})
  await page.screenshot({path:path.join(OUT,'home-'+width+'.png'),fullPage:true})
  if(width===390||width===1440){
   await page.screenshot({path:path.join(OUT,'hero-'+width+'.png')})
   await page.evaluate(()=>location.hash='#/detail/wedding/live')
   await page.waitForTimeout(100)
   await page.locator('.worry-section summary').first().click()
   assert.equal(await page.locator('.worry-section details').first().getAttribute('open'),'')
   await page.locator('.reviews-section').scrollIntoViewIfNeeded()
   const reviewTrack=page.locator('#reviewTrack')
   assert.equal(await reviewTrack.locator('.review-set').count(),2,'review orbit contains two identical sets for a seamless loop')
   assert.equal(await reviewTrack.locator('.review-capture').count(),22,'all eleven reviews are duplicated for continuous motion')
   assert.equal(await page.locator('.review-carousel-controls button').count(),2,'review carousel includes previous and next buttons')
   const beforeTransform=await reviewTrack.locator('.review-loop').evaluate(el=>getComputedStyle(el).transform)
   await page.locator('[data-review-next]').click()
   await page.waitForTimeout(700)
   const afterTransform=await reviewTrack.locator('.review-loop').evaluate(el=>getComputedStyle(el).transform)
   assert.notEqual(afterTransform,beforeTransform,'review cards move with the next control')
   await page.screenshot({path:path.join(OUT,'review-'+width+'.png')})
   assert.equal(await page.locator('[data-video]').count(),0,'wedding video does not open a popup')
   assert.match(await page.locator('.detail-inline-video iframe').getAttribute('src'),/5ZuTmQWCRJk/)
   await page.screenshot({path:path.join(OUT,'video-'+width+'.png')})
   await page.evaluate(()=>location.hash='#/choose/wedding')
   await page.waitForTimeout(100)
   await page.locator('.film-format-section').scrollIntoViewIfNeeded()
   await page.evaluate(async()=>{for(const img of document.querySelectorAll('.film-format-grid img')){img.loading='eager'}await Promise.all([...document.querySelectorAll('.film-format-grid img')].map(img=>img.decode().catch(()=>{})))})
   await page.screenshot({path:path.join(OUT,'composition-'+width+'.png')})
   await page.locator('.film-format-card').nth(1).click()
   assert.match(page.url(),/#\/detail\/wedding\/making$/)
   assert.equal(await page.locator('.selected-format-section').count(),0,'choice opens a clean detail page without the duplicate format summary')
   assert.equal(await page.locator('.film-format-card').count(),0,'selected detail does not repeat both choices')
   assert.match(await page.locator('#process').textContent(),/녹음 메이킹 영상 촬영.*인서트 컷.*녹음실 메이킹 컷/s)
   await page.locator('.fixed-price a').click()
   assert.match(page.url(),/#\/event\/wedding\/making$/)
   assert.equal(await page.locator('[data-film-format="making"]').isChecked(),true,'selected detail format carries into booking')
   assert.match(await page.locator('#bookingSummary').textContent(),/영상 구성.*녹음 메이킹 클립/s)
   assert.match(await page.locator('.package-list').textContent(),/인서트 컷 촬영.*녹음실 메이킹 촬영.*인트로·아웃트로 타이포/s)
   assert.doesNotMatch(await page.locator('.package-list').textContent(),/인터뷰 촬영|전하는 편지 촬영/)
   await page.locator('.event-benefits').scrollIntoViewIfNeeded()
   if(width<=800){
    assert.equal(await page.locator('#bookingSummary').evaluate(el=>getComputedStyle(el).position),'static','mobile package summary remains in the document')
    assert.equal(await page.locator('.mobile-summary-label').isVisible(),true)
    assert.equal(await page.locator('.price-formula').isVisible(),false,'mobile package summary only shows the configuration and normal price')
    const fixedStrip=await page.locator('.booking-mobile-bar').boundingBox()
    assert.equal(await page.locator('.booking-mobile-bar').evaluate(el=>getComputedStyle(el).position),'fixed')
    assert.ok(Math.abs(fixedStrip.y+fixedStrip.height-page.viewportSize().height)<=1,'dark mobile price strip follows the viewport')
   }else{
    const stickyCalculator=await page.locator('#bookingSummary').boundingBox()
    assert.equal(await page.locator('#bookingSummary').evaluate(el=>getComputedStyle(el).position),'sticky')
    assert.ok(stickyCalculator.y>=0&&stickyCalculator.y<=130,'desktop price calculator remains visible while scrolling')
   }
   await page.locator('[data-event="blog"]').check()
   assert.match(await page.locator('.price-formula').textContent(),/290,000원.*30,000원.*260,000원/s)
   await page.locator('[data-option="rush"]').check()
   await page.locator('[data-option="bridal-ar"]').check()
   assert.match(await page.locator('.price-formula').textContent(),/330,000원/)
   assert.match(await page.locator('#mobilePrice').textContent(),/290,000원.*40,000원.*330,000원/s)
   const formatMsg=await page.evaluate(()=>consultationText())
   assert.match(formatMsg,/선택한 영상 구성 : 녹음 메이킹 클립/)
   await page.evaluate(()=>location.hash='#/event/solo')
   await page.waitForTimeout(100)
   assert.deepEqual(await page.locator('[data-song-option]').evaluateAll(nodes=>nodes.map(n=>n.dataset.songOption)),['lyrics','lyrics-making'])
   assert.equal(await page.locator('.song-option-card img').count(),2,'song options show lyric-video and recording-making images')
   await page.locator('[data-song-option="lyrics"]').check()
   await page.locator('[data-event="blog"]').check()
   await page.locator('#bookingRatio').selectOption('70')
   assert.match(await page.locator('.price-formula').textContent(),/130,000/)
   await page.evaluate(()=>scrollTo(0,0))
   await page.screenshot({path:path.join(OUT,'booking-'+width+'.png'),fullPage:true})
   await page.locator('#contactSource').selectOption({label:'인스타그램'})
   await page.locator('#contactName').fill('하영')
   await page.locator('#eventDate').fill('2026-12-20')
   await page.locator('#contactPurpose').selectOption({label:'축가'})
   await page.locator('#requestMessage').fill('낮은 키로 준비하고 싶어요')
   await page.evaluate(()=>{window.open=()=>({})})
   await page.locator('#consultForm button[type="submit"]').click()
   const msg=await page.evaluate(()=>consultationText())
   assert.ok(msg.includes('130,000원')&&msg.includes('70%')&&msg.includes('2026-12-20')&&msg.includes('하영')&&msg.includes('상담 시 협의')&&msg.includes('낮은 키'))
   await page.waitForFunction(()=>document.querySelector('.copy-toast')?.textContent.includes('복사'))
   await page.screenshot({path:path.join(OUT,'consult-'+width+'.png')})
   await page.evaluate(()=>location.hash='#/detail/solo')
   await page.waitForTimeout(100)
   await page.waitForSelector('.ratio-section:not(.is-loading)')
   assert.deepEqual(await page.locator('[data-ratio]').evaluateAll(nodes=>nodes.map(n=>n.dataset.ratio)),['30','50','70','100'])
   assert.equal(await page.locator('[data-ratio-audio]').count(),1,'ratio selector uses one stable audio player')
   assert.match(await page.locator('.ratio-guide').textContent(),/70%와 100%.*완전한 립싱크.*마이크를 꺼/s,'ratio guide explains the popular choices and 100% lip sync')
   assert.deepEqual(await page.evaluate(()=>Object.entries(RATIO_SOURCES).map(([ratio,src])=>ratio+':'+src.split('/').pop()).sort()),['100:voice-100.wav','30:voice-30.wav','50:voice-50.wav','70:voice-70.wav'],'ratio player uses the four supplied original WAV files')
   assert.ok(await page.locator('#ratioAudio').evaluate(audio=>audio.seekable.length===1&&audio.seekable.end(0)>32),'prepared audio supports seeking across the full sample')
   await page.locator('#ratioAudio').evaluate(async audio=>{if(audio.readyState<1)await new Promise(resolve=>audio.addEventListener('loadedmetadata',resolve,{once:true}));audio.currentTime=12})
   await page.locator('[data-ratio="100"]').click()
   await page.waitForFunction(()=>document.querySelector('#ratioAudio')?.dataset.ratioAudio==='100'&&document.querySelector('#ratioAudio').currentTime>=11.5)
   assert.equal(await page.locator('#ratioAudio').getAttribute('data-ratio-audio'),'100')
   assert.ok(await page.locator('#ratioAudio').evaluate(audio=>audio.currentTime>=11.5),'ratio change keeps the current playback position')
   assert.equal(await page.locator('#ratioAudio').evaluate(audio=>audio.paused),false,'new ratio continues playing')
   await page.waitForTimeout(220)
   assert.equal(await page.locator('[data-ratio-audio]').evaluateAll(audios=>audios.filter(audio=>!audio.paused).length),1,'only one ratio audio plays after the fade transition')
   assert.ok(await page.locator('#ratioAudio').evaluate(audio=>audio.volume>.99),'new ratio restores the playback volume after fading')
   for(const ratio of ['30','50','70']){
    const beforeSwitch=await page.locator('#ratioAudio').evaluate(audio=>audio.currentTime)
    await page.locator('[data-ratio="'+ratio+'"]').click()
    await page.waitForFunction(expected=>document.querySelector('#ratioAudio')?.dataset.ratioAudio===expected,ratio)
    await page.waitForTimeout(220)
    assert.ok(await page.locator('#ratioAudio').evaluate((audio,start)=>audio.currentTime>=start-.15,beforeSwitch),'rapid ratio sequence keeps its playback position')
    assert.equal(await page.locator('[data-ratio-audio]').evaluateAll(audios=>audios.filter(audio=>!audio.paused).length),1,'rapid ratio sequence never leaves overlapping audio')
   }
   const continuedAt=await page.locator('#ratioAudio').evaluate(audio=>audio.currentTime)
   await page.waitForTimeout(350)
   assert.ok(await page.locator('#ratioAudio').evaluate((audio,start)=>audio.currentTime>start,continuedAt),'playback keeps advancing after ratio change')
   await page.locator('.wordmark').click()
   await page.locator('.situation-pill').first().click()
   assert.match(page.url(),/#\/choose\/wedding$/)
   await page.locator('#headerBack').click()
   await page.waitForTimeout(100)
   assert.match(page.url(),/#\/$/)
   report.checks.push(width+'px interactions passed')
  }
  await page.close()
 }
 const motionPage=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'no-preference'})
 await motionPage.goto('http://127.0.0.1:4173/?v=89#/detail/duo',{waitUntil:'domcontentloaded'})
 await motionPage.locator('.review-loop').waitFor()
 await motionPage.waitForTimeout(350)
 const motionStart=await motionPage.locator('.review-loop').evaluate(el=>getComputedStyle(el).transform)
 await motionPage.waitForTimeout(600)
 const motionEnd=await motionPage.locator('.review-loop').evaluate(el=>getComputedStyle(el).transform)
 assert.notEqual(motionEnd,motionStart,'reviews move continuously without a rigid timed jump')
 assert.match(await motionPage.locator('.review-crop-06 img').first().getAttribute('src'),/review-06-clean\.webp$/,'review six uses the clean crop without the captured Instagram arrow')
 await motionPage.close()
 assert.deepEqual(report.errors,[])
 assert.deepEqual(report.brokenAssets,[])
 console.log(JSON.stringify(report,null,2))
 fs.writeFileSync(path.join(OUT,'report.json'),JSON.stringify(report,null,2))
 } finally {await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1})
